SCBJ-7/SCBJ-FE

.github/workflows/playwright.yml, .gitignore, package-lock.json, package.json, playwright.config.ts, src/main.tsx, tests/example.spec.ts
vitest의 경우 아직 좀 더 검증이 필요한 것 같아 설치를 미뤘습니다.
=> [#2] chore : 라이브러리 설치

.github/workflows/firebase-hosting-pull-request.yml
=> [#14] firebase pr preview 임시 비활성화

README.md
close #17 
1. Readme에 추가
```
> display: flex; <br>
> min-width: 360px; <br>
> max-width: 768px; <br>
- 규칙
1. 컴포넌트의 width는 가변값(%) 사용을 권장합니다.
2. 컴포넌트의 height만 고정값(px)를 사용합니다.
3. 되도록 Layout(Wrapper)가 되는 레이아웃에 min-width/max-width 너비를 설정합니다.(내용이 되는 컴포넌트엔 %만 설정할 수 있도록)
```
2. 노션에 추가 (노션엔 레퍼런스도 같이 있습니다)
[노션 링크](https://www.notion.so/Convention-a86fc4810c2045d5ba57a73bd2cbbe25?pvs=4#937ad553cde34c16b90fa59442a5b610)
마크다운 스크린샷:
<br>
<br>
<br>
<br>
노션 스크린샷:
=> [#17] 반응형 디자인 전략 readme에 추가

package-lock.json, package.json
=> [#23] styled-component 삭제(잘못된 라이브러리)

package-lock.json, package.json
close https://github.com/SCBJ-7/SCBJ-FE/issues/24
프레이머 모션을 설치해놨습니다. 양도글 작성 시 꼭 필요할 거 같습니다.
=> [#24] framer-motion 설치

src/main.tsx, src/styles/globalStyle.ts, src/styles/theme.ts
close #27 
styles 폴더에 globalStyle.ts와 theme.ts 파일 생성하고
main에서 import 하는 방식으로 변경되었습니다.
=> [#27] GlobalStyle & Theme 외부 파일 생성

.github/workflows/firebase-hosting-pull-request.yml, package-lock.json, package.json, src/pages/detailPage/index.tsx, src/pages/homePage/index.tsx, src/pages/myPage/index.tsx, src/pages/notFoundPage/index.tsx, src/pages/searchPage/index.tsx, src/pages/signUpPage/index.tsx, src/pages/transferPurchasePage/index.tsx, src/pages/transferSalePage/index.tsx, src/pages/transferWritingPage/index.tsx, tests/e2eTests/example.spec.ts
close #30 
**main에서 pull 받으신 뒤 npm i 를 해주시기 바랍니다!**
playwright가 계속 찾던 @rollup/rollup-linux-x64-gnu 이녀석을 optionalDependency에 추가해주었습니다.
참고 블로그 : https://answers.netlify.com/t/react-vite-build-fails-because-of-rollup-rollup-linux-x64-gnu/107504/6
에러 관련 이미지
추가로 github action이 PR에 접근 가능하도록 권한을 주어 PR Preview시 에러가 발생하지 않습니다.
이 기능을 이용해 추후 vitest의 test coverage를 PR시 확인할 수 있도록 자동화를 고려중입니다.
테스트 해보니 PR preview도 잘 뜨고 playwright도 에러를 발생시키지 않습니다. 예~~
=> [#30] firebase PR 코드 수정 및 playwright 테스트 코드 수정

package-lock.json, package.json, src/pages/signUpPage/SignUp.style.ts, src/pages/signUpPage/SignUp.tsx
close #59 
react-hook-form is best / pull 받으시면 npm i  로 라이브러리 설치하셔야 합니다!
정해진게 없어 회원가입 이후 로그인 페이지로 리다이렉션 하도록 작성했습니다.
axios의 경우 아직 틀이 잡힌것 같지 않아 axiosInstance를 사용하지 않고 axios를 import 해서 사용했습니다.
또한 회원가입이라는 특성상 캐싱을 할 필요가 없다고 생각해 react-query를 사용하지 않았습니다.
=> [#59] 회원가입 페이지 react-hook-form 적용 / API 연동 마무리

README.md
=> [#91] 중간 제출 리드미 작성

src/App.tsx, src/apis/fetchTransferItems.ts, src/apis/fetchTransferItems_realApi.ts, src/apis/postTransferItems.ts, src/mocks/handler.ts, src/pages/transferWritingPage/TransferWriting.tsx, src/pages/transferWritingPricePage/TransferWritingPrice.tsx, src/pages/transferWritingPricePage/accountSection/AccountSection.style.ts, src/pages/transferWritingPricePage/accountSection/AccountSection.tsx, src/pages/transferWritingPricePage/agreementSection/AgreementSection.style.ts, src/pages/transferWritingPricePage/agreementSection/AgreementSection.tsx, src/pages/transferWritingPricePage/checkBox/CheckBoxSection.tsx, src/pages/transferWritingPricePage/firstPriceTag/FirstPriceTag.style.ts, src/pages/transferWritingPricePage/firstPriceTag/FirstPriceTag.tsx, src/pages/transferWritingPricePage/inputSection/InputSection.tsx, src/pages/transferWritingPricePage/paymentSection/PaymentSection.style.ts, src/pages/transferWritingPricePage/paymentSection/PaymentSection.tsx, src/pages/transferWritingPricePage/secondPriceTag/SecondPriceTag.tsx
close https://github.com/SCBJ-7/SCBJ-FE/issues/84
노가다 작업을 했읍니다..
```javascript
const submitHandler = () => {
if (!readyToSubmit) { // 제출 버튼 활성화 여부 state가 활성화되지 않았다면
const firstPriceNum = Number(firstPrice.split(",").join(""));
const secondPriceNum = Number(secondPrice.split(",").join(""));
const downTimeAfterNum = Number(downTimeAfter);
let message = [<></>]; // 토스트 메시지 배열
if (!firstPriceNum) {
message = [<>1차 가격을 설정해주세요</>];
setToastConfig({
isShow: true,
isError: true,
strings: message,
});
if (firstInputRef.current) {
(firstInputRef.current as HTMLInputElement).focus();
// + 스크롤 상단으로 올리기
}
// 1차 가격이 판매가보다 높을 때
} else if (firstPriceNum > selectedItem.purchasePrice) {
message = [<>판매가격이 구매가보다 높아요! 판매가격을 확인해주세요</>];
setToastConfig({
isShow: true,
isError: true,
strings: message,
});
if …
```
=> [#84] 가격설정 페이지 토스트 에러처리, 인터랙션 구현, 실제 api 주소 코드작성

src/pages/myPage/MyPage.style.ts, src/pages/myPage/MyPage.tsx
close #143 
야놀자 연동을 너무 잘 만들어주셔서 navigate만 했습니다! 감사합니당
이 부분도 유저정보 전역 상태로 관리하면 api 호출 없이 진행하겠습니다.
=> [#143] 마이페이지 내 야놀자 연동 버튼 활성화

src/apis/axiosInstance.ts, src/pages/myPage/MyPage.style.ts, src/pages/myPage/MyPage.tsx, src/pages/signInPage/SignIn.tsx
close #141 
```javascript
// axiosInstance.ts
if (!accessToken) {
alert("다시 로그인 해 주세요."); // or 로그인
window.location.href = `${PATH.LOGIN}?redirect=${window.location.pathname}`;
}
```
```javascript
// SignIn.tsx
const [searchParams] = useSearchParams();
const redirectUrl = searchParams.get("redirect");
...
const 로그인함수 = () => {
...
// 로그인 성공 시
if (redirectUrl) {
navigate(redirectUrl);
return;
}
navigate(PATH.ROOT);
...
}
```
위와 같이 pathname을 로그인 페이지로 넘겨주고, 로그인 페이지에서 redirect라는 search 파라미터가 있다면 해당 페이지로 리다이렉션 하도록 진행했습니다.
추가적으로 로그인 파일에서 리팩터링 해야 하는 부분은 추후에 진행하겠습니다.
=> [#141] 로그인 후 이전 페이지로 리다이렉션 로직 추가

src/apis/axiosInstance.ts, src/apis/logout.ts, src/components/account/enterAccountInfo/EnterAccountInfo.style.ts, src/pages/myPage/MyPage.style.ts, src/pages/myPage/MyPage.tsx, src/pages/myPage/info/Info.style.ts, src/pages/myPage/info/Info.tsx, src/pages/myPage/manage/Manage.tsx, src/pages/myPage/manage/editAccount/EditAccount.tsx, src/pages/signInPage/SignIn.tsx
close #138 
```javascript
const logoutConfirmHandler = async () => {
try {
await logout();
localStorage.clear();
handleToast(false, ["로그아웃 성공"]);
navigate(PATH.ROOT);
} catch (err) {
handleToast(true, [<>로그아웃 실패. 잠시 후 다시 시도해 주세요</>]);
} finally {
setShowLogoutModal(false);
}
};
```
로그아웃 시 로컬스토리지의 모든 값을 삭제했습니다.
그리고 우선 홈 화면으로 이동시켰는데 로그인 화면으로 이동하는 게 좋은지는 PM분과 상의 후에 수정하겠습니다.
=> [#138] 로그아웃 구현

src/firebase.ts
close https://github.com/SCBJ-7/SCBJ-FE/issues/158
콘솔키 노출만 했습니다!
=> [#158] 파이어베이스키 노출

src/pages/signInPage/SignIn.tsx
=> [#157] 로그인 페이지 로고 링크 추가

src/pages/homePage/navToSearchSection/NavToSearchSection.tsx
close https://github.com/SCBJ-7/SCBJ-FE/issues/167
코드 한 줄 바꿔서.. 바로 반영하겠습니다!
요거 누르면
여기로 가게 했습니다.
=> [#167] 홈 - 검색필터 => 일정선택 페이지로 라우팅 변경

src/pages/transferWritingPage/TransferWriting.tsx, src/pages/transferWritingPricePage/TransferWritingPrice.tsx, src/pages/transferWritingPricePage/inputSection/InputSection.tsx, src/pages/transferWritingPricePage/secondPriceTag/SecondPriceTag.tsx
close https://github.com/SCBJ-7/SCBJ-FE/issues/166
=> [#166]양도글 작성 QA 진행

src/apis/fetchRoom.ts
=> [#175] fix: axios instance 사용 안함

src/apis/fetchMainItems.ts, src/main.tsx, src/pages/homePage/Home.tsx, src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx, src/pages/homePage/percentAnimator/PercentAnimator.tsx, src/pages/transferWritingPricePage/TransferWritingPrice.tsx
close https://github.com/SCBJ-7/SCBJ-FE/issues/177
api명세서에는 값이 없을 때 null값을 주기로 되어있어서 null만 없앴는데, 실제로는 빈 배열을 받아서 0이 된 문제였습니다.
=> [#177] 메인페이지에 0 뜨는 버그 수정

src/pages/homePage/Home.tsx, src/pages/homePage/itemCarousel/ItemCarousel.tsx, src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx, src/pages/homePage/percentAnimator/PercentAnimator.tsx
close https://github.com/SCBJ-7/SCBJ-FE/issues/179
=> [#179] 캐로셀 할인률 반대로 나오는 이슈 수정

index.html, src/apis/fetchPayment.ts, src/components/modal/Modal.style.ts, src/components/modal/Modal.tsx, src/constants/api.ts, src/constants/path.ts, src/hooks/api/mutation/usePaymentMutation.ts, src/hooks/api/query/usePaymentQuery.ts, src/main.tsx, src/pages/paymentPage/Payment.tsx, src/pages/roomDetailPage/components/roomNavBar/RoomNavBar.tsx, src/routes/router.tsx
=> [#170] 결제 승인, 실패

src/apis/fetchMainItems.ts, src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.style.ts, src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx, src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.style.ts, src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.tsx, src/pages/transferWritingPage/TransferWriting.tsx, src/pages/transferWritingPage/transferItem/TransferItem.tsx, src/pages/transferWritingPricePage/TransferWritingPrice.tsx, src/pages/transferWritingPricePage/enterAccountInfo/EnterAccountInfo.tsx, src/pages/transferWritingPricePage/secondPriceTag/SecondPriceTag.tsx, src/pages/transferWritingSuccessPage/TransferWritingSuccess.tsx, src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.style.ts, src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.tsx
=> [#185] 바텀시트 플로우, 메인페이지 qa 대응, 양도글 작성 qa 대응

src/pages/homePage/percentAnimator/PercentAnimator.tsx
=> [#185] Math.round처리 부족한 곳 처리

src/pages/paymentPage/Payment.tsx
=> [#188] 결제 완료 시 paymentHistoryId 추가

src/pages/transferWritingPricePage/TransferWritingPrice.tsx
=> [#191] 반올림 처리 및 주석 추가

src/routes/router.tsx
=> [#195] 글로벌 서스펜스 추가 및 모든 서스펜스에 로딩컴포넌트 추가

src/pages/paymentPage/Payment.tsx
=> [#188] action 조건문 추가

src/components/layout/Layout.tsx
=> [#199] 임시 공통 헤더 네비바 분리

src/pages/passwordResetPage/PasswordReset.tsx, src/pages/passwordResetPage/components/fieldValues/FieldValues.tsx, src/pages/passwordResetPage/components/passwordResetSubmitBtn.tsx/PasswordResetSubmitBtn.tsx
=> [#169] 비밀번호 찾기 페이지 리팩토링

src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.tsx
=> [#201] qa대응 - 계좌번호 등록 사파리에서 안 되는 이슈

src/pages/homePage/Home.tsx, src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx, src/pages/homePage/percentAnimator/PercentAnimator.tsx
=> [#201] 정렬 수정 및 모바일 캐로셀 대응

src/pages/paymentPage/components/userInfoSection/UserInfoSection.tsx, src/pages/roomDetailPage/RoomDetail.style.ts
=> [#188] 입력필드 수정 시 체크박스 해제되도록 수정

src/pages/homePage/itemCarousel/ItemCarousel.style.ts, src/pages/homePage/weekendCarousel/WeekendCarousel.style.ts
=> [#207]캐로셀 버튼컨테이너 클릭 전파 가능하게 수정

src/App.tsx, src/components/scrollToTop/ScrollToTop.tsx
=> [#206] 페이지 마다 scroll to top 적용

src/pages/homePage/itemCarousel/ItemCarousel.style.ts, src/pages/homePage/itemCarousel/ItemCarousel.tsx, src/utils/isMobile.ts
=> [#210] 모바일에선 버튼 가리기

src/apis/fetchAlarm.ts
=> [#213] fetchAlarm에 instance 제거

src/pages/homePage/itemCarousel/ItemCarousel.style.ts
=> [#fix] carousel pan-y제거

src/pages/homePage/itemCarousel/ItemCarousel.style.ts, src/pages/homePage/itemCarousel/itemCarouselUnit/ItemCarouselUnit.tsx
=> [#217] carousel 모바일 터치 이벤트 제한

src/apis/fetchSaleDetail.ts, src/apis/fetchSaleList.ts, src/components/layout/header/HeaderTop.tsx, src/constants/api.ts, src/constants/path.ts, src/hooks/api/query/useSaleDetailQuery.ts, src/pages/myPage/MyPage.tsx, src/pages/paymentSuccessPage/components/PaymentSuccessButton/PaymentSuccessButton.tsx, src/pages/saleDetailPage/SaleDetail.tsx, src/pages/searchPage/Search.tsx, src/pages/transferPurchasePage/TransferPurchase.style.ts, src/pages/transferPurchasePage/TransferPurchase.tsx, src/pages/transferPurchasePage/components/puchaseItem/PuchaseItem.tsx, src/pages/transferSalePage/TransferSale.style.ts, src/pages/transferSalePage/TransferSale.tsx, src/pages/transferWritingSuccessPage/TransferWritingSuccess.tsx, src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.tsx, src/routes/router.tsx
=> 구매내역 판매내역 NoResult처리

manifest.json, offline.html, public/pwabuilder-sw.js
=> [#225] PWA 아이콘 변경, 캐시 사용

src/pages/homePage/mainHeader/MainHeader.tsx
close https://github.com/SCBJ-7/SCBJ-FE/issues/232
=> [#232] 타입에러 수정 후 재배포

src/pages/signInPage/SignIn.tsx
=> [#236] 토큰 임시로 렌더링 되도록

src/pages/signInPage/SignIn.tsx
=> [#236] fcm 토큰 발급 후 백엔드에 전달

src/components/layout/Layout.style.ts, src/components/layout/header/HeaderTop.tsx, src/pages/homePage/mainHeader/MainHeader.style.ts, src/pages/myPage/components/myPageNav/MyPageNav.style.ts, src/pages/saleDetailPage/SaleDetail.style.ts, src/pages/searchFilterPage/SearchFilter.style.ts, src/pages/searchFilterPage/SearchFilter.tsx, src/pages/searchFilterPage/components/calendarModal/CalendarModal.style.ts, src/pages/searchPage/Search.style.ts, src/pages/searchPage/components/searchBar/SearchBar.style.ts, src/pages/searchPage/components/searchModalButton/SearchModalButton.style.ts, src/pages/searchPage/components/searchNav/SearchNav.style.ts
=> 검색 검색필터 판매 상세 페이지 container padding top 수정 & 알람 아이콘 변경 및 navigate 추가 & 검색페이지 hover이벤트 추가 & 달력 모달 css 수정 

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml, src/App.tsx
=> [#249] ghAction 환경변수 재설정

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml
=> [#249] env 시크릿키 위치 수정

src/apis/fetchAlarm.ts, src/apis/fetchHasAlarm.ts, src/pages/alarmPage/AlarmPage.style.ts, src/pages/alarmPage/AlarmPage.tsx, src/pages/homePage/mainHeader/MainHeader.tsx
close https://github.com/SCBJ-7/SCBJ-FE/issues/248
note보단 실제 코드에 짧게 코멘트만 하겠습니다.
=> [#248] 알람 api, 알람여부 api 고치기

src/utils/getNotificationPermission.ts
=> [#257] 배포 테스트용

src/pages/homePage/Home.style.ts, src/pages/homePage/Home.tsx, src/pages/homePage/itemCarousel/ItemCarousel.tsx, src/pages/homePage/sequenceSection/SequenceSection.style.ts, src/pages/homePage/sequenceSection/SequenceSection.tsx, src/pages/homePage/weekendCarousel/WeekendCarousel.tsx, src/pages/homePage/weekendCarousel/weekendCarouselUnit/WeekendUnit.style.ts
close https://github.com/SCBJ-7/SCBJ-FE/issues/181
close https://github.com/SCBJ-7/SCBJ-FE/issues/184
=> [#181] 캐로셀 인디케이터 클릭 시 해당 섹션으로 이동 기능 추가, 주말특가 캐로셀 화살표 다음 버튼 눌렀을 때 넘어가는 범위 일정치 않은 버그 수정

src/apis/postAccount.ts, src/pages/transferWritingPricePage/TransferWritingPrice.tsx, src/pages/transferWritingSuccessPage/accountBottomSheet/AccountBottomSheet.tsx, src/store/store.ts
close https://github.com/SCBJ-7/SCBJ-FE/issues/263
=> [#263] 첫 계좌 등록 시 새로운 계좌로 등록할 때 useNavigate의 state를 활용. (아이폰 사파리에서 안 되는 버그 해결)

index.html
=> [#277] 모바일 뷰포트 확대기능 제한

src/apis/logout.ts
=> [#281] 로그아웃 시 fcmToken 미포함으로 변경

src/apis/logout.ts, src/constants/api.ts, src/hooks/common/useCarousel.ts, src/pages/signInPage/SignIn.tsx
=> [#283] 토큰 저장 후 로그아웃 시 제거

src/apis/logout.ts, src/pages/signInPage/SignIn.tsx
=> [#289] 토큰 저장 로직 제거

src/hooks/common/useCarousel.ts, src/pages/myPage/MyPage.tsx
=> [#287] 마이페이지 비로그인 시 로그인 유도 화면

src/components/Helmet/Helmet.tsx
=> [#295] data-react-helmet=true 설정

package-lock.json, package.json, src/components/redirect/Redirect.tsx, src/hooks/api/useUserInfoQuery.ts, src/main.tsx, src/pages/connectYanoljaPage/verificationPage/VerificationPage.tsx, src/pages/purchaseDetailPage/PurchaseDetail.style.ts, src/pages/purchaseDetailPage/PurchaseDetail.tsx, src/pages/saleDetailPage/SaleDetail.tsx, src/pages/saleDetailPage/saleInfo/SaleInfo.tsx, src/routes/router.tsx
=> [#96] Redirection 컴포넌트 구현

src/App.tsx, src/components/toast/Toast.tsx, src/pages/paymentPage/Payment.tsx, src/store/store.ts
=> [#275] path가 바뀔 때마다 토스트 상태 리셋

.gitignore, playwright.config.ts, tests/e2eTests/example.spec.ts, tests/e2eTests/global.setup.ts, tests/e2eTests/models/LoginPage.ts, tests/e2eTests/models/SignupPage.ts, tests/e2eTests/specs/authentication/login.spec.ts, tests/e2eTests/specs/authentication/register.spec.ts, tests/unitTestsSrc/VerificationPage.spec.tsx, tests/unitTestsSrc/useEmailVerification.spec.tsx, tsconfig.json, vite.config.ts
=> [#317] 로그인/회원가입 e2e 테스트

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml, package-lock.json, package.json, src/apis/fetchMainItems.ts, src/constants/api.ts, tsconfig.json
close #321 
"https://3.34.147.187.nip.io" -> "https://3.34.XXX.XXX.XXX.XX"
.env 파일에 VITE_BASE_URL로 설정하였습니다.
그리고 `constants/api.ts`에 api주소 하드코딩되어 있던거 환경변수로 바꿨습니다. 
```javascript
// in constants/API
// export const BASE_URL = "https://3.34.147.187.nip.io";  <- 하드코딩 되어있던 api주소
export const BASE_URL = import.meta.env.VITE_BASE_URL; // 환경변수로 변경
export const END_POINTS = {
LOGIN: "/v1/members/signin",
...
```
또 firebase 콘솔에서 환경변수 추가해야된다고 헷갈렸는데 
github action으로 firebase에 제공해줘야했습니다.
```javascript
if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
runs-on: ubuntu-latest
env:
VITE_BASE_URL: "${{secrets.VITE_BASE_URL}}" // 추가!
VITE_APIKEY: "${{secrets.VITE_APIKEY}}"
VITE_AUTH_DOMAIN: "${{secrets.VITE_AUTH_DOMAIN}}"
VITE_PROJECT_ID: "${{secrets.VITE_PROJECT_ID}}"
```
=> [#321] API 주소 교체, 환경변수로 변경 후 Github Action workflow로 배포 시 제공 설정

src/apis/fetchMainItems.ts, src/components/layout/Layout.tsx, src/components/noResult/NoResult.tsx, src/hooks/common/useCarousel.ts, src/pages/homePage/Home.style.ts, src/pages/homePage/Home.tsx, src/pages/homePage/weekendCarousel/WeekendCarousel.tsx
close #323 
현재 weekend item이 0개일 경우 방어를 못함.
0개인 경우 주말 특가 컨테이너를 렌더하지 않게 처리
=> [#323] 주말 특가가 0개일 때는 주말특가 컨테이너 숨기기

.github/workflows/firebase-hosting-merge.yml, .github/workflows/firebase-hosting-pull-request.yml, public/firebase-messaging-sw.js
=> [#332] workflow 수정

src/pages/searchPage/Search.style.ts, src/pages/searchPage/components/searchItem/SearchItem.style.ts, src/pages/searchPage/components/searchItem/SearchItem.tsx, src/types/searchList.ts
=> 검색페이지 리펙터링

tsconfig.json
ts linting을 유연하게 잡아서 빌드 실패를 줄이고자 합니다.
hotfix로 바로 머지하겠습니당
=> HotFix: tsconfig 에러 처리 유연하게 변경

src/apis/cancelSale.ts, src/components/ui/bottom-sheet/styles.ts, src/components/ui/dialog/dialog-root.tsx, src/components/ui/dialog/index.ts, src/hooks/api/useDiscontinueQuery.tsx, src/hooks/api/useStockQuery.ts, src/pages/roomDetailPage/components/discontinuePopup/DiscontinuePopup.tsx, src/pages/roomDetailPage/components/roomNavBar/RoomNavBar.tsx, src/pages/saleDetailPage/saleButton/SaleButton.tsx
close #364 
상세 페이지의 판매 취소 액션을 추가했습니다.
- [feat: 판매취소 모달 추가](https://github.com/SCBJ-7/SCBJ-FE/commit/d1d4e7124d4ffdf7f49cbb941c5b69996fb26135)
- [feat: 판매취소 쿼리 훅 추가](https://github.com/SCBJ-7/SCBJ-FE/commit/c9bcbcfab53f4c5db6c5a025bcae1ad3c06694d7)
- [feat: 판매취소 액션 추가](https://github.com/SCBJ-7/SCBJ-FE/commit/20940c48a9ae9cf35a351b547d864bad398b2c53)
판매자/구매자 액션 분리가 필요합니다 🫠
=> Feat: 상세페이지 판매취소 기능 추가

src/pages/roomDetailPage/components/roomMap/RoomMapPopup.style.ts, src/pages/wishListPage/components/wishCard/WishCard.tsx
지도 컨테이너가 화면(786px)에 맞게 보이도록 수정합니다
- [design: 지도 컨테이너 수정](https://github.com/SCBJ-7/SCBJ-FE/commit/cb1088854b5a3b29c5dff8e6c16a08983352398d)
=> Fix: 지도 컨테이너 UI 수정

src/pages/transferWritingPage/TransferWriting.tsx, src/pages/transferWritingPricePage/checkBox/CheckBoxSection.style.ts
=> feat: 0원 막기

src/pages/transferWritingPricePage/checkBox/CheckBoxSection.style.ts
=> [#351] 0원일 때 넘어가는 현상 수정

src/hooks/common/useChangePage.ts, src/pages/transferWritingPricePage/priceSection/PriceSection.tsx, src/pages/transferWritingPricePage/transferNavigation/transferNavigation.tsx
=> fix: phaseType import 수정
